### PR TITLE
Make segments accessible

### LINKED ISSUE #7: Make segments accessible
Either make `UIImageView`s accessible (with traits `UIAccessibilityTraitButton`), or if it doesn't work, create `UIAccessibilityElement` with a corresponding frame for each `UIImageView`.

### PR DESCRIPTION
**Pull request by andris-zalitis**
Close #7

### CODE REVIEW

**Comment by andris-zalitis** [comment]
@salutis, @ruslankmlv ready for review

**Comment by andris-zalitis** [comment]
Will add accessibility titles after #12

**Comment by rudolf-adamkovic** [comment]
In review.

File: SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift [hunk 1]
```diff
@@ -82,6 +82,16 @@ class SlidingSegmentedControlTests: XCTestCase {
         XCTAssertEqual(slidingSegmentedControl.imageViews.map {$0.contentMode}, [.center, .center, .center])
     }
 
+    func testImageViewsIsAccessibilityElement() {
+        let slidingSegmentedControl = SlidingSegmentedControl(images: [UIImage(), UIImage()])
+        XCTAssertEqual(slidingSegmentedControl.imageViews.map { $0.isAccessibilityElement }, [true, true])
```
Comment (rudolf-adamkovic) [inline SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift]: Not a big fan of "clever" code in tests. Compare:

Complex:
```swift
let slidingSegmentedControl = SlidingSegmentedControl(images: [UIImage(), UIImage()])
XCTAssertEqual(slidingSegmentedControl.imageViews.map { $0.isAccessibilityElement }, [true, true])
```

Simple:
```swift
let image1 = UIImage()
let image2 = UIImage()

let slidingSegmentedControl = SlidingSegmentedControl(images: [image1, image2])

XCTAssertTrue(image1.isAccessibilityElement)
XCTAssertTrue(image2.isAccessibilityElement)
```

Now, if you were to maintain 1000 new unit tests, which style would you prefer? 😄 

P.S. An alternative to 2 asserts (not a fan as it is more complex again):
```swift
XCTAssertTrue(image1.isAccessibilityElement && image2.isAccessibilityElement)
```

**Review by rudolf-adamkovic — CHANGES_REQUESTED** [review]

**Comment by rudolf-adamkovic** [comment]
Strange, GitHub is showing my review comment as "outdated".

File: SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift (hunk 1 above)
Comment (andris-zalitis) [reply SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift]: I don't think this simple `map` should be considered complex or _clever_ code. I use it because it's concise.

Consider this example:
```Swift
    func testImageViewsImagesV1() {
        let images = [UIImage(), UIImage()]
        let slidingSegmentedControl = SlidingSegmentedControl(images: images)
        XCTAssertEqual(slidingSegmentedControl.imageViews.flatMap { $0.image }, images)
    }

    func testImageViewsImagesV2() {
        let images = [UIImage(), UIImage()]
        let slidingSegmentedControl = SlidingSegmentedControl(images: images)
        guard slidingSegmentedControl.imageViews.count == 2 else {
            XCTFail("Expected 2 image views")
            return
        }
        XCTAssertEqual(slidingSegmentedControl.imageViews[0].image, images[0])
        XCTAssertEqual(slidingSegmentedControl.imageViews[1].image, images[1])
    }
```
If I don't do guard, test will be trap with EXC_BAD_INSTRUCTION if `imageViews` haven't been populated, so for a good test, I do need it. Hence this, I try to test against arrays themselves when possible and doing a simple `map` or a `flatMap` feels a lot better than making test twice as big.

In the particular example that you commented on the difference in size is minimal, I agree, but we're all about consistency right (we either allow maps in tests or we don't)?

By the way - using _clever_ code is not considered good also for production (because it is harder to maintain). So if we consider any map to be _clever_ code, we would simply need to avoid it everywhere, but I doubt you'd want that. ;)

Comment (andris-zalitis) [reply SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift]: From my experience test files often tend to be quite bigger than files of the types they test.

I think that bigger tests, even if they are simple, also add some cognitive overhead if compared to smaller tests which are more concise (but not overly _clever_). With smaller tests, you can navigate more quickly and see more tests per each screen, so I think conciseness is a good thing.

- `map` is concise and in some cases it lets us avoid unnecessary `guard` statement.
- AFAIK `map` is not being considered _clever coding_ by Swift community

So I would vote for using simple `map`s and `flatMap`s in tests.

Comment (rudolf-adamkovic) [reply SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift]: @andris-zalitis 

Your claim about `EXC_BAD_INSTRUCTION` is **false**. 

We don't need that `guard` at all:

```swift
func testImageViewsImage() {
    let images = [UIImage(), UIImage()]
    let slidingSegmentedControl = SlidingSegmentedControl(images: images)
    XCTAssertEqual(slidingSegmentedControl.imageViews.first?.image, images[0])
    XCTAssertEqual(slidingSegmentedControl.imageViews.last?.image, images[1])
}
```

Tests with **no logic** are best.

P.S. Even better, one could simplify further:

```swift
// Do we have images views for all supplied images?
func testImageViewCount() {
    let images = [UIImage(), UIImage()]
    let slidingSegmentedControl = SlidingSegmentedControl(images: images)
    XCTAssertEqual(slidingSegmentedControl.imageViews.count, 2)
}

// Do we set proper images for image views?
func testImageViewsImages1() {
    let images = [UIImage(), UIImage()]
    let slidingSegmentedControl = SlidingSegmentedControl(images: images)
    XCTAssertEqual(slidingSegmentedControl.imageViews.first?.image, images[0])
}

...
```

Comment (andris-zalitis) [reply SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift]: @salutis 
> Your claim about EXC_BAD_INSTRUCTION is false.
> 
> We don't need that guard at all:

Good point. But gotta say it wouldn't work with 3 images.

Also, note that both of your examples **test less** than the example with a `flatMap`.

1. The first example would pass when we have more than 2 elements in `imageViews`, we just need first and last have corresponding images.
2. The second example, on the other hand, passes also if code sets only the image for the first image view.

To be honest, I don't see why we should accept this sacrifice. The intention of my test was to make sure of two things:
1. That I have _n_ `UIImageView`s created for _n_ `UIImage`s
2. That each `UIImageView`'s `image` is equal to the corresponding `UIImage`.

I think that `flatMap` is the best tool for that. The question is - does the cognitive overhead that it introduces outweighs the precision and conciseness that comes with it?

To me, the answer is "no", because overhead is small and I love the precision, not having multiple asserts and not dealing with guards when I have n images. If to you after all this discussion the answer is still "yes", then I'll make updates :)

Comment (rudolf-adamkovic) [reply SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift]: @andris-zalitis 

> Also, note that both of your examples test less [...]

My bad, here you go:

```swift
func testImageViewCount1() {
    let slidingSegmentedControl = SlidingSegmentedControl(images: [UIImage()])
    XCTAssertEqual(slidingSegmentedControl.imageViews.count, 1)
}

func testImageViewCount2() {
    let slidingSegmentedControl = SlidingSegmentedControl(images: [UIImage(), UIImage()])
    XCTAssertEqual(slidingSegmentedControl.imageViews.count, 2)
}

func testImageViewsImage1() {
    let image = UIImage()
    let slidingSegmentedControl = SlidingSegmentedControl(images: [image, UIImage()])
    XCTAssertEqual(slidingSegmentedControl.imageViews.first?.image, image)
}

func testImageViewsImage2() {
    let image = UIImage()
    let slidingSegmentedControl = SlidingSegmentedControl(images: [UIImage(), image])
    XCTAssertEqual(slidingSegmentedControl.imageViews.last?.image, image)
}
```

Simple, focused, no logic.

Comment (andris-zalitis) [reply SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift]: @salutis 
That works! But 4 lines of tests replaced by 18. Man, you really must be hating those `flatMap`s 😄 

Getting rid of them as promised.

**Comment by andris-zalitis** [comment]
@salutis 
I have addressed the issues you pointed to. Ready for a review!

File: SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift (hunk 1 above)
Comment (rudolf-adamkovic) [reply SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift]: @andris-zalitis I love them. Just not in tests. 😄

**Comment by rudolf-adamkovic** [comment]
In review.

File: SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift [hunk 2]
```diff
@@ -72,14 +72,56 @@ class SlidingSegmentedControlTests: XCTestCase {
...
+    }
+
+    func testImageViewsContentMode2() {
+        let slidingSegmentedControl = SlidingSegmentedControl(images: [UIImage(), UIImage()])
+        XCTAssertEqual(slidingSegmentedControl.imageViews.last?.contentMode, .center)
+    }
+
+    func testImageViewsIsAccessibilityElement1() {
+        let slidingSegmentedControl = SlidingSegmentedControl(images: [UIImage(), UIImage()])
+        XCTAssertEqual(slidingSegmentedControl.imageViews.first?.isAccessibilityElement, true)
```
Comment (rudolf-adamkovic) [inline SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift]: Consider using `XCTAssertTrue` instead of `XCTAssertEqual`.

File: SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift [hunk 3]
```diff
@@ -72,14 +72,56 @@ class SlidingSegmentedControlTests: XCTestCase {
...
+    }
+
+    func testImageViewsIsAccessibilityElement2() {
+        let slidingSegmentedControl = SlidingSegmentedControl(images: [UIImage(), UIImage()])
+        XCTAssertEqual(slidingSegmentedControl.imageViews.last?.isAccessibilityElement, true)
```
Comment (rudolf-adamkovic) [inline SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift]: Consider using `XCTAssertTrue` instead of `XCTAssertEqual`.

**Review by rudolf-adamkovic — CHANGES_REQUESTED** [review]

File: SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift (hunk 2 above)
Comment (andris-zalitis) [reply SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift]: To use XCTAssertTrue I either need to use first! (suboptimal) or guard (verbose), that's why I opted to use XCTAssertEqual instead.

File: SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift (hunk 3 above)
Comment (andris-zalitis) [reply SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift]: Same issue as above.

File: SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift (hunk 2 above)
Comment (rudolf-adamkovic) [reply SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift]: Yeah, Apple is a bit behind with XCTest when used with Swift.

But why not add `XCTAssertTrue` that works with optionals instead?

Something like:
```swift
func XCTAssertTrue(_ expression: Bool?, file: StaticString = #file, line: UInt = #line) {
    guard let expression = expression else {
        XCTFail("XCTAssertTrue failed: nil is not equal to true")
        return
    }
    XCTAssertTrue(expression, "", file: file, line: line)
}
```

File: SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift (hunk 3 above)
Comment (rudolf-adamkovic) [reply SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift]: Ditto.

File: SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift (hunk 2 above)
Comment (rudolf-adamkovic) [reply SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift]: Ideally, we can start writing [`apple-test-assertions`](https://github.com/eggheadgames/apple-test-assertions) now.

**Comment by andris-zalitis** [comment]
@salutis Thanks for the nice suggestion regarding improving the readability of the tests! I have made the requested changes.

**Review by rudolf-adamkovic — APPROVED** [review]
@andris-zalitis Good job!

P.S. Please, try to keep commit messages short. The last one ended up like this:

screen shot 2016-12-16 at 16 26 24

**Comment by andris-zalitis** [comment]
@salutis 

Thank you for the review and merge! :)

> P.S. Please, try to keep commit messages short. The last one ended up like this:

I know. Not pretty, but informative! :) I could skip "Improve readability" but then it would miss the reason for the change. How would you say in this case?

**Comment by rudolf-adamkovic** [comment]
@andris-zalitis 

> I know. Not pretty, but informative! :) I could skip "Improve readability" but then it would miss the reason for the change. How would you say in this case?

That's what "body" of a commit message is for, not title.

GitHub will recognize it and **will show as a text block underneath**.

```
Summarize changes in around 50 characters or less

More detailed explanatory text, if necessary. Wrap it to about 72
characters or so. In some contexts, the first line is treated as the
subject of the commit and the rest of the text as the body. The
blank line separating the summary from the body is critical (unless
you omit the body entirely); various tools like `log`, `shortlog`
and `rebase` can get confused if you run the two together.

Explain the problem that this commit is solving. Focus on why you
are making this change as opposed to how (the code explains that).
Are there side effects or other unintuitive consequences of this
change? Here's the place to explain them.
```

[Source](http://chris.beams.io/posts/git-commit/)
